version: '3.9'

services:
  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: tenants
    secrets:
      - db_root_password

  php-apache:
    depends_on:
      - db
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app/:/var/www/html/
    environment:
      CONFIG_FILE: /run/secrets/m3saas_config
    secrets:
      - m3saas_config

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080

  hive-mq:
    build:
      context: ./hive-mq
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1883:1883 # TCP - MQTT
      - 8000:8000 # Websocket - MQTT
      - 9090:9090 # HTTP - Heartbeat

secrets:
  db_root_password:
    file: ./secrets/db_root_password.secret
  m3saas_config:
    file: ./secrets/config.json.secret

volumes:
    db_data:
